vocalink-test-app-1:
    tty: true
    image: phooper0001/vocalink-test-app-1:0.1
    stdin_open: true
    ports:
    - "127.0.0.1:8081:8081"
    labels:
      io.rancher.container.pull_image: always
vocalink-test-app-2:
    tty: true
    image: phooper0001/vocalink-test-app-2:0.1
    stdin_open: true
    links:
    - vocalink-test-app-1
    labels:
      io.rancher.container.pull_image: always
vocalink-test-app-3:
    tty: true
    image: phooper0001/vocalink-test-app-3:0.1
    stdin_open: true
    links:
    - vocalink-test-app-2
    labels:
      io.rancher.container.pull_image: always
